version: '3.8'

services:
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - api

  api:
    image: simulator
    ports:
      - "8080:8080"